spring.application.name=CalculatorAPI

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.namespace=local
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.tracing.sampling.probability=1.0
