spring.docker.compose.enabled=false

management.otlp.metrics.export.enabled=false
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-lgtm:4318/v1/traces
management.tracing.sampling.probability=1.0

logging.pattern.console=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSS} %5p ${PID:- } --- [%t] trace_id=%X{traceId:-} span_id=%X{spanId:-} trace_flags=01 %logger{36} --- %m%n
